<br/> 
  <h3><?php echo $this->msg; var_dump($this->imms);?></h3>
  <br />
  <br />
     <table>
      <thead>
        <tr>
            <th>Immobile</th>
            <th>Piano</th>         
            <th>Zona</th>
            <th>Piano di fuga</th>
            <th>Piano di fuga alternativo</th> 
            <th>Assegna</th> 
        </tr>
      </thead>
      <?php foreach ($this->imms as $imm){
            
            echo "<tr>";
            echo "<td>". $imm['Immobile']  ."</td>";
            echo "<td>". $imm['Id_piano']      ."</td>";
            echo "<td>". $imm['Zona']   ."</td>";
            echo "<td>". $imm['Piano_di_fuga'] ."</td>";
            echo "<td>". $imm['Piano_di_fuga_alternativo'] ."</td>";
            echo "<td>". $imm['Utente'] ."</td>";
            echo "<td>". $imm['Tipo_Catastrofe'] ."</td>";
            echo "<td>
                    <a  href=".
                        $this->url(array(
                            'controller' => 'staff',
                            'action'     => 'assign',
                            'immobile'   => $imm['Immobile'],
                            'floor'      => $imm['Id_piano'],
                            'zone'       => $imm['Zona']
                            ), 
                            'default',true).">
                    <img width=32 height=32 src=".$this->baseURL()."/images/trashicon.png>
                    </a>
                  </td>";
            echo "</tr>";      
        } ?>
  </table>
        <?php echo $this->fileform ?>
        <br />
        <br />
        <a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'deletealternativeplan',
                        'immobile'   => $this->selimm,
                        'floor'      => $this->selfloor,
                        'zone'       => $this->selzone
                        ), 
                        'default',true
                    ); 
            ?>" title="">Elimina il piano di zona alternativo</a>
                                            
