<br/> 
  <h3><?php echo $this->msg; ?></h3>
  <br />
  <br />
  
  <?php if($this->selimm==null) :?>
     <table>
      <thead>
        <tr>
            <th>Immobile</th>
            <th>Piano</th>         
            <th>Zona</th>

            <th>Assegna</th> 
        </tr>
      </thead>
      <?php foreach ($this->imms as $i){
            foreach ($i as $imm){
            echo "<tr>";
            echo "<td>". $imm['Immobile']  ."</td>";
            echo "<td>". $imm['Id_piano']      ."</td>";
            echo "<td>". $imm['Zona']   ."</td>";
            echo "<td>
                    <a  href=".
                        $this->url(array(
                            'controller' => 'staff',
                            'action'     => 'assignescapeplan',
                            'immobile'   => $imm['Immobile'],
                            'floor'      => $imm['Id_piano'],
                            'zone'       => $imm['Zona']
                            ), 
                            'default',true).">
                    <img width=32 height=32 src=".$this->baseURL()."/images/home.png>
                    </a>
                  </td>";
            echo "</tr>";      
        }
      } ?>
  </table>
        <?php else :?>
            <p>Ok ora carica il piano alternativo per </p><br />
            <p>Immobile : <?= $this->selimm ?></p>
            <p>Piano : <?= $this->selfloor ?></p>
            <p>Zona : <?= $this->selzone ?></p>
        <?php echo $this->fileform ?>
       
        <br />
        <br />
        <a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'deletealternativeplan',
                        'immobile'   => $this->selimm,
                        'floor'      => $this->selfloor,
                        'zone'       => $this->selzone
                        ), 
                        'default',true
                    ); 
            ?>" title="">Elimina il piano di zona alternativo</a>
          <?php endif ?>                                   
