<?php $this->headScript()
    ->appendFile($this->baseUrl('js/jquery-1.12.4.min.js'),$type = 'text/javascript')
    ->appendFile($this->baseUrl('js/Staff/evacuation.js'),$type = 'text/javascript')
    ->captureStart() ?>
    
    function autoFill()
    {
        $.ajax({
        type : 'POST',
        url : "<?php $this->url(array('controller'=>'staff','action'=>'getdata'))?>",
        data : {'Immobile': $("#immobili").val(),'isAjax':true},
        dataType : 'json',
        success : populate()
    });
       
    }
    
    <?php $this->headScript()->captureEnd() ?>

<h3>Benvenuto utente <?php echo $this->authInfo('Username')?> seleziona il </h3><br />
<h3>piano su cui vuoi attivare la procedura di evacuazione</h3>
<br />
<br />
<ul>
    <?php 
    foreach ($this->imms as $key => $value) :?>
    <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'evacuation',
                        'immobile'      =>$value
                        ), 
                        'default',true
                    ); 
                 ?>" title=""><?php echo 'Immobile'.$value?></a></li>
                
            
        <?php endforeach ?>
</ul>
<ul>
<?php 
      
 if($this->selimm!=null){
    
        foreach ($this->floors as $key => $value) :?>
            
            <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'evacuation',
                        'immobile'   => $this->selimm,
                        'floor'      =>$value
                        ), 
                        'default',true
                    ); 
            ?>" title=""><?php echo 'Floor'.$value;?></a></li>
                    
        <?php endforeach; 
}?>
        
<?php if($this->selfloor!=null):?>
    
    <?php echo 'Immobile selezionato'.$this->selimm.'<br/>';
    echo 'Piano selezionato'.$this->selfloor.'<br/>';?>
    <a class="evac" href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'setevacuation',
                        'immobile'   => $this->selimm,
                        'floor'      => $this->selfloor,
                        'evac'       => 1
                        ), 
                        'default',true
                    ); 
                 ?>" title="Segnala l'allerta"><?php echo $this->imgRenderer('alert.png',array('width'=>'50','height'=>'50'));?></a>                                
    
    
    <a class="evac" href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'setevacuation',
                        'immobile'   => $this->selimm,
                        'floor'      => $this->selfloor,
                        'evac'       => 0
                        ), 
                        'default',true
                    ); 
                 ?>" title="Tutto ok"><?php echo $this->imgRenderer('safe.png',array('width'=>'50','height'=>'50'));?></a>
    
    <?php endif ?>                                        

<br/> 
  <h3><?php echo $this->msg; ?></h3>
  <?php
  for($a=0; $a<6; $a++){
      echo "<br/>";
  }?>