<br/> 
  <h3><?php echo $this->msg; ?></h3>
    <table>
      <thead>
        <tr>
            <th>Immobile</th>
            <th>Piano</th>         
            <th>Numero di persone</th>

        </tr>
      </thead>
      <?php foreach ($this->imms as $info){
            echo "<tr>";
            echo "<td>". $info['Immobile']  ."</td>";
            echo "<td>". $info['Id_piano']  ."</td>";
            echo "<td>". $info['Num']       ."</td>";
            echo "</tr>";      
        } 
       ?>
  </table>
  
  <table>
      <thead>
        <tr>
            <th>Immobile</th>
            <th>Piano</th>
            <th>Zona</th>         
            <th>Numero di persone</th>

        </tr>
      </thead>
      <?php foreach ($this->zones as $info){
              foreach($info as $ex){  
                echo "<tr>";
                echo "<td>". $ex['Immobile']  ."</td>";
                echo "<td>". $ex['Id_piano']  ."</td>";
                echo "<td>". $ex['Zona']      ."</td>";
                echo "<td>". $ex['Num']       ."</td>";
                
                echo "</tr>"; 
              }     
        } 
        ?>
  </table>
  
  <table>
      <thead>
        <tr>
            <th>Immobile</th>
            <th>Piano</th>
            <th>Zona</th>         
            <th>Data</th>
            <th>Ora</th>
            <th>Utente</th>
            <th>Tipo</th>

        </tr>
      </thead>
      <?php $cat='';
       foreach ($this->alerts as $info){
              foreach($info as $ex){
                  switch ($ex['Tipo_Catastrofe']) {
                      
                      case 1:
                          $cat='Allagamento';
                          break;
                     case 2:
                          $cat='Crollo';
                          break;
                     case 3:
                          $cat='Incendio';
                          break;
                     case 4:
                          $cat='Fumo';
                          break; 
                      
                  }  
                echo "<tr>";
                echo "<td>". $ex['Immobile']  ."</td>";
                echo "<td>". $ex['Id_Piano']  ."</td>";
                echo "<td>". $ex['Codice_Zona']      ."</td>";
                echo "<td>". $ex['Data_Segnalazione']       ."</td>";
                echo "<td>". $ex['Ora_Segnalazione']       ."</td>";
                echo "<td>". $ex['Utente']       ."</td>";
                echo "<td>". $cat       ."</td>";
                echo "</tr>"; 
              }     
        } 
        ?>
  </table>