<br/> 
  <h3><?php echo $this->msg; ?></h3>
    <table>
      <thead>
        <tr>
            <th>Immobile</th>
            <th>Piano</th>         
            <th>Numero di persone</th>

        </tr>
      </thead>
      <?php foreach ($this->imms as $info){
            echo "<tr>";
            echo "<td>". $info['Immobile']  ."</td>";
            echo "<td>". $info['Id_piano']  ."</td>";
            echo "<td>". $info['Num']       ."</td>";
            echo "</tr>";      
        } 
       ?>
  </table>
  
  <table>
      <thead>
        <tr>
            <th>Immobile</th>
            <th>Piano</th>
            <th>Zona</th>         
            <th>Numero di persone</th>

        </tr>
      </thead>
      <?php foreach ($this->zones as $info){
              foreach($info as $ex){  
                echo "<tr>";
                echo "<td>". $ex['Immobile']  ."</td>";
                echo "<td>". $ex['Id_piano']  ."</td>";
                echo "<td>". $ex['Zona']      ."</td>";
                echo "<td>". $ex['Num']       ."</td>";
                
                echo "</tr>"; 
              }     
        } 
        ?>
  </table>
  <?php
  for($a=0; $a<6; $a++){
      echo "<br/>";
  }?>