<br/> 
  <h3><?php echo $this->msg; ?></h3>
    <table id="tableusers">
      <thead>
        <tr>
            <th>Username</th> <th>Nome</th>         
            <th>Cognome</th><th>Categoria</th> 
            <th>Modifica</th><th>Cancella</th> 
        </tr>
      </thead>
      <?php/* foreach ($this->alert as $alert){
                // Non stampa l'admin
            if($user['Categoria'] == 3)
                continue;
            switch($user['Categoria']){
                case 1: $user['Categoria'] = 'Utente'; break;
                case 2: $user['Categoria'] = 'Staff'; break;
            }
            echo "<tr>";
            echo "<td>". $user['Username']  ."</td>";
            echo "<td>". $user['Nome']      ."</td>";
            echo "<td>". $user['Cognome']   ."</td>";
            echo "<td>". $user['Categoria'] ."</td>";
            echo "<td>
                    <a href=".
                        $this->url(array(
                            'controller' => 'user',
                            'action'     => 'editprofile'
                            ), 
                            'default',true).">
                    <img width=32 height=32 src=".$this->baseURL()."/images/editicon.png>
                    </a>
                  </td>";
            echo "<td>
                    <a href=#>
                        <img width=32 height=32 src=".$this->baseURL()."/images/trashicon.png>
                    </a>
                  </td>";
            echo "</tr>";      
        }*/ ?>
  </table>
  
  <?php
  for($a=0; $a<6; $a++){
      echo "<br/>";
  }?>