<br/> 
  <h3><?php echo $this->msg; ?></h3>
    <table id="tableusers">
      <thead>
        <tr>
            <th>Codice Segnalazione</th>
            <th>Data Segnalazione</th>         
            <th>Ora Segnalazione</th>
            <th>Id Piano</th>
            <th>Zona</th> 
            <th>Utente</th>
            <th>Tipo catastrofe</th> 
            <th>Cancella</th> 
        </tr>
      </thead>
      <?php foreach ($this->alert as $alert){
           /*    
            if($['Categoria'] == 3)
                continue;
            switch($user['Categoria']){
                case 1: $user['Categoria'] = 'Utente'; break;
                case 2: $user['Categoria'] = 'Staff'; break;
            }*/
            echo "<tr>";
            echo "<td>". $alert['Codice_Segnalazione']  ."</td>";
            echo "<td>". $alert['Data_Segnalazione']      ."</td>";
            echo "<td>". $alert['Ora_Segnalazione']   ."</td>";
            echo "<td>". $alert['Id_Piano'] ."</td>";
			echo "<td>". $alert['Codice_Zona'] ."</td>";
			echo "<td>". $alert['Utente'] ."</td>";
			echo "<td>". $alert['Tipo_Catastrofe'] ."</td>";
            echo "<td>
                    <a href=".
                        $this->url(array(
                            'controller' => 'staff',
                            'action'     => 'removealert',
                            'cod_al'		 => $alert['Codice_Segnalazione']
                            ), 
                            'default',true).">
                    <img width=32 height=32 src=".$this->baseURL()."/images/trashicon.png>
                    </a>
                  </td>";
            echo "</tr>";      
        } ?>
  </table>
  
  <?php
  for($a=0; $a<6; $a++){
      echo "<br/>";
  }?>