<div id="staff" class="container">
   
        <div class="title">
            <h2>Sito per la gestione dei locali chiusi</h2>
            
        </div>

    <div id="welcome" class="container">
        <div class="title">
            <h2>Benvenuti nel nostro sito</h2>
        </div>
        <p>
        Sito per la gestione delle misure di sicurezza in caso di emergenza in sede lavorativa. I dipendenti delle società
        che utilizzano questa applicazione, possono registrarsi al sito, accedendo così alle funzioni pensate per semplificare
        e velocizzare le procedure di emergenza. Gli utenti possono registrare la loro posizione all'interno di ogni immobile,
        segnalare eventuali situazioni di emergenza e ottenere in tal caso i percorsi di evacuazione dell'edificio, inviati
        tempestivamente dai membri dello staff.
        </p>
         <div class="boxA"> <?php echo $this->imgRenderer('pic01.jpg',array('width'=>'300','height'=>'450'));?> </div>
        
        <div class="boxB"><?php echo $this->imgRenderer('pic02.jpg',array('width'=>'300','height'=>'450'));?> </div>
        
        <div class="boxC"> <?php echo $this->imgRenderer('pic03.jpg',array('width'=>'300','height'=>'450'));?> </div>
        <div>
        <strong>Relazione del progetto </strong><a href="<?php echo $this->docRenderer('Relazione.pdf');?>" target="_blank">Link alla relazione </a>
        </div>
    </div>