<?php $this->headScript()
    ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
    ->appendFile($this->baseUrl('js/functions.js'))
    ->captureStart() ?>

$(function()
{
    var actionUrl='<? echo $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
    var formName='<?php echo $this->loginForm->getName() ?>';
    $(":input").on('blur', function(event) {
    var formElementId = $(this).attr('id');
    doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>


<div id="staff" class="container">
    <h3>Accedi al sito</h3>
    <p>Utilizza questa form per accedere al sito</p>
    <?php echo $this->loginForm ?>
</div>
<div>
    <a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'signup'
                        ), 
                        'default',true
                    ); 
                 ?>">Iscriviti adesso</a>
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                     
                     
</div>