<div id="staff" class="container">
    <h3>Accedi al sito</h3>
    <p>Utilizza questa form per accedere al sito</p>
    <?php echo $this->loginForm ?>
</div>
<div>
    <a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'signup'
                        ), 
                        'default',true
                    ); 
                 ?>">Iscriviti adesso</a>
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                     
                     
</div>