<!--<?php $this->headScript()
    ->appendFile($this->baseUrl('js/jquryfun.js'))
    ->appendFile($this->baseUrl('js/jquery-1.12.4.min.js'))
    //->captureStart() ?>

$(function()
{
    var actionUrl='<? echo $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
    var formName='<?php echo $this->loginForm->getName() ?>';
    $(":input").on('blur', function(event) {
    var formElementId = $(this).attr('id');
    doValidation(formElementId, actionUrl, formName);
    });
});

<?php//$this->headScript()->captureEnd() ?>
-->

<div id="staff" class="container">
    <br /><br />
    <h3>Accedi al sito</h3>
    <br />
    <p>Utilizza questa form per accedere al sito</p>
    <?php echo $this->loginForm ?>
</div>
<div>
    <a id="signupref" href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'signup'
                        ), 
                        'default',true
                    ); 
                 ?>">Iscriviti adesso</a>
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                 <br />
                     
                     
</div>