
<br/> 
<h3>&nbsp;&nbsp;Benvenuto utente <?php echo $this->authInfo('Username')?> sei pregato di inserire la tua posizione</h3>
<br />
<br />
<h4>Seleziona l'immobile e di seguito il piano</h4>
<ul>
    <?php 
    foreach ($this->imms as $key => $value) :?>
    <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'setinitialposition',
                        'immobile'      =>$value
                        ), 
                        'default',true
                    ); 
                 ?>" title=""><?php echo 'Immobile'.$value?></a></li>
                
            
        <?php endforeach ?>
</ul>
<ul>
<?php 
      
 if($this->selimm!=null){
    
        foreach ($this->floors as $key => $value) :?>
            
            <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'setinitialposition',
                        'immobile'   => $this->selimm,
                        'floor'      =>$value
                        ), 
                        'default',true
                    ); 
            ?>" title=""><?php echo 'Floor'.$value;?></a></li>
                    
        <?php endforeach; 
}?>
        
<?php if($this->selfloor!=null){
    echo '<h4>Immobile selezionato'.$this->selimm.'<br/>';
    echo 'Piano selezionato'.$this->selfloor.'</h4>';
    echo $this->mapRenderer($this->map);
                                         
    echo $this->printArea($this->schema,$this->selimm,$this->selfloor,'public'); 
                                            
}?>
<br />
<br />
<br />
<br />
<br /><br /><br />
