<div id="staff" class="container">

    <p><b>Chi siamo?</b></p>    

La nostra società si occupa della gestione di siti web. Nasce nel 2008 dall'idea di un gruppo di giovani
ingegneri informatici, desiderosi di mettere in pratica le proprie competenze, per realizzare qualcosa di
utile e funzionale. L'applicazione da noi sviluppata gioca un ruolo centrale nell'ambito della sicurezza
sul lavoro, offrendo un servizio che riteniamo sia importante per i dipendenti delle aziende che richiedono
il nostro aiuto. Questo sito è appunto uno strumento attraverso il quale l'utenza accede in modo veloce e
comodo alle misure di sicurezza da prendere in caso di emergenze in sede lavorativa.

Perchè scegliere noi?

Serietà e professionalità ci contraddistinguono, oltre alla passione con cui ci dedichiamo a quello 
che facciamo. Dai primi semplici lavori, fatti un po' per hobby, è nato poi l'entusiasmo che ci ha portato a
proseguire e, supportati da un percorso universitario specifico e da studi mirati sul settore, nonché da
progetti sperimentali nella realizzazione di siti web e dei servizi ad esso correlati, ci siamo fatti strada
in questo mondo. L'esperienza e allo stesso tempo l'apertura alle novità, alimentata da un continuo progresso,
che spesso tende a travolgere la realtà lavorativa consolidata, fanno sì che ci sia sempre la necessità di doversi
mettere alla prova, di doversi confrontare con le innovazioni e vagliarne la validità ai fini pratici. La nostra
società si propone, per questo, di essere un'azienda sempre in espansione, pronta ad accettare e ad accogliere
le nuove sfide della tecnologia con entusiasmo sempre rinnovato, senza dare mai l'impressione di essere arrivati,
perché sarà in quel momento che avremo la certezza di non far più parte del gioco che conta!
   
</div>