<br/>
<ul>
  
	<!-- Sezione Amministratore -->
	
	<li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'imm'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="0" title="">Gestisci Immobili</a></li>
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'getuser'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="1" title="">Gestione Utenti</a></li>
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'insertuser'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="2" title="">Inserisci Utenti</a></li>  
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'faq'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="3" title="">&nbsp;&nbsp;Gestisci FAQ&nbsp;&nbsp;</a></li> 
     <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'logout'
                        ), 
                        'default',true
                    ); 
               ?>" accesskey="3" title="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Logout&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>                  
</ul>
