<br/>
<ul>
	<li id='0'><a href="" accesskey="1" title="">Invia Segnalazione</a></li>
	<li id='1'><a href="" accesskey="2" title="">Cambia Posizione</a></li>
	<li id='2'><a href="" accesskey="3" title="">Modifica Profilo</a></li>
	<li id='3'><a href="" accesskey="4" title="">Vedi Percorso di Fuga</a></li> 
	<hr/>
	<li id='4'><a href="" accesskey="5" title="">Pannello di Controllo</a></li>
	<li id='5'><a href="" accesskey="6" title="">Assegna Percorsi</a></li>  
	<li id='6'><a href="" accesskey="7" title="">Gestisci Segnalazioni</a></li> 
	<li id='7'><a href="" accesskey="8" title="">Attiva l'Evacuazione</a></li> 
	<hr/>
	<li id='8'><a href="" accesskey="9" title="">Gestisci Immobili</a></li>
    <li id='9'><a href="" accesskey="10" title="">Gestisci Utenti</a></li>  
    <li id='10'><a href="" accesskey="" title="">Gestisci FAQ</a></li> 
</ul>
