<ul>
	<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'index'
                        ), 
                        'default',true
                    ); 
                 ?>"
		accesskey="1" title="">Homepage</a></li>
		<li class="active"><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index'), 
                        'default',true
                    ); 
                 ?>"
        accesskey="2" title="">Login</a></li>
</ul>
