<br/>
<ul>
  
    <!-- Sezione Staff -->
    
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'panel'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="0" title="">Pannello di Controllo</a></li>
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'assignescapeplan'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="1" title="">Assegna Percorsi</a></li>  
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'managealert'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="2" title="">Gestisci Segnalazioni</a></li> 
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'evacuation'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="3" title="">Attiva l'Evacuazione</a></li> 
  <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'logout'
                        ), 
                        'default',true
                    ); 
               ?>" accesskey="4" title="">Logout</a></li>                  
</ul>
