<br/>
<ul>
    
    <!-- Sezione Utenti -->
    
    <li id='0'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'sendalert'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="1" title="">Invia Segnalazione</a></li>
    <li id='1'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'changeposition'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="2" title="">Cambia Posizione</a></li>
    <li id='2'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'editprofile'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="3" title="">Modifica Profilo</a></li>
    <li id='3'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'viewescapeplan'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="4" title="">Vedi Percorso di Fuga</a></li> 
    <hr/>
    
    
    <!-- Sezione Staff -->
    
    <li id='4'><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'panel'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="5" title="">Pannello di Controllo</a></li>
    <li id='5'><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'assignescapeplan'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="6" title="">Assegna Percorsi</a></li>  
    <li id='6'><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'managealert'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="7" title="">Gestisci Segnalazioni</a></li> 
    <li id='7'><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'evacuation'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="8" title="">Attiva l'Evacuazione</a></li> 
</ul>
