<ul>
	<li id='0', class="active"><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'index'
                        ), 
                        'default',true
                    ); 
                 ?>"
		accesskey="1" title="">Homepage</a></li>
	<li id='1'><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'who'), 
                        'default',true
                    ); 
                 ?>"
		accesskey="2" title="">Chi siamo</a></li>
	<li id='2'><a
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'where'), 
                        'default',true
                    ); 
                 ?>"
		accesskey="3" title="">Dove Siamo</a></li>
	<li id='3'><a
        href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'faq'), 
                        'default',true
                    ); 
                 ?>"
        accesskey="4" title="">FAQ</a></li>
    <li id='4'><a
        href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login'), 
                        'default',true
                    ); 
                 ?>"
        accesskey="5" title="">Area Riservata</a></li>
   
</ul>
