<br/>
<ul>
	    
    <!-- Sezione Utenti -->
    
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'sendalert'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="1" title="">Invia Segnalazione</a></li>
    <li ><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'changeposition'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="2" title="">Cambia Posizione</a></li>
<li class="menu"><a href="<?php echo $this->url(array(
                        'controller' => 'user',
                        'action'     => 'editprofile',
                        'username'   => $this->authInfo('Username'),
                        'filled'     => true,
                        'completed'  => false
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="3" title="">Modifica Profilo</a></li>
    <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'viewescapeplan'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="4" title="">Vedi Percorso di Fuga</a></li> 
     <li class="menu"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'logout'
                        ), 
                        'default',true
                    ); 
               ?>" accesskey="5" title="">Logout</a></li> 
</ul>
