<br/>
<ul>
	    
    <!-- Sezione Utenti -->
    
    <li id='0'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'sendalert'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="1" title="">Invia Segnalazione</a></li>
    <li id='1'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'changeposition'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="2" title="">Cambia Posizione</a></li>
    <li id='2'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'editprofile'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="3" title="">Modifica Profilo</a></li>
    <li id='3'><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'viewescapeplan'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="4" title="">Vedi Percorso di Fuga</a></li> 
</ul>
