<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
</head>
<body>
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="#">Area Riservata</a></h1>
		</div>
		<div id="menu">
		    <?= $this->render('_topnavmain.phtml') ?>
	    </div>
	
<div id="wrapper">
    <div id="usermenu">
        <?= $this->render($this->menu) ?>
    </div>
    <div id="wrapper-content"
	   <?php echo $this->layout()->content; ?>
    </div>
</div>
<div id="copyright" class="container">
	<p>&copy; Untitled. All rights reserved. | Progetto di Tecnologie Web Gruppo_08</p>
</div>
</body>
</html>
