<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
</head>
<body>
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="#">WebProject</a></h1>
		</div>
		<div id="menu">
		    <?= $this->render('_topnavmain.phtml') ?>
		
	</div>
	<div id="banner" class="container">
	    <?php $this->imgRenderer('banner.jpg',array('width'=>'100%','height'=>'100%'));?>
	    <span>Maecenas vitae orci vitae<br />
		tellus feugiat eleifend</span></div>
</div>
<div id="wrapper">
	<?php echo $this->layout()->content; ?>
</div>
<div id="copyright" class="container">
	<p>&copy; Untitled. All rights reserved. | Progetto di Tecnologie Web Gruppo_08</p>
</div>
</body>
</html>
