
<br/> 
  <h3><?php echo $this->msg; ?></h3>
  <h3><?php echo $this->welcomemsg; ?></h3>
  
  
<h6><a href="<?php echo $this->url(array(
                        'controller' => 'user',
                        'action'     => 'deleteposition'
                        ), 
                        'default',true
                    ); 
                 ?>" title="">Cancella la tua posizione</a></h6>

<ul>
    <?php 
    foreach ($this->imms as $key => $value) :?>
    <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'changeposition',
                        'immobile'      =>$value
                        ), 
                        'default',true
                    ); 
                 ?>" title=""><?php echo 'Immobile'.$value?></a></li>
                
            
        <?php endforeach ?>
</ul>
<ul>
<?php 
      
 if($this->selimm!=null){
    
        foreach ($this->floors as $key => $value) :?>
            
            <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'changeposition',
                        'immobile'   => $this->selimm,
                        'floor'      =>$value
                        ), 
                        'default',true
                    ); 
            ?>" title=""><?php echo 'Floor'.$value;?></a></li>
                    
        <?php endforeach; 
}?>
        
<?php if($this->selfloor!=null){
    echo 'Immobile selezionato'.$this->selimm.'<br/>';
    echo 'Piano selezionato'.$this->selfloor.'<br/>';
    echo $this->mapRenderer($this->map);
                                         
    echo $this->printArea($this->schema,$this->selimm,$this->selfloor,'user'); 
                                            
}?>
