
<br/> 
  <h3><?php echo $this->msg; ?></h3>

<ul>
    <?php 
    foreach ($this->imms as $key => $value) :?>
    <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'changeposition',
                        'immobile'      =>$value
                        ), 
                        'default',true
                    ); 
                 ?>" title=""><?php echo 'Immobile'.$value?></a></li>
                
            
        <?php endforeach ?>
</ul>
<ul>
<?php 
      
 if($this->selimm!=null){
    
        foreach ($this->floors as $key => $value) :?>
            
            <li class="show"><a href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'changeposition',
                        'immobile'   => $this->selimm,
                        'floor'      =>$value
                        ), 
                        'default',true
                    ); 
            ?>" title=""><?php echo 'Floor'.$value;?></a></li>
                    
        <?php endforeach; 
}?>
        
<?php if($this->selfloor!=null){
    echo 'Immobile selezionato'.$this->selimm.'<br/>';
    echo 'Piano selezionato'.$this->selfloor.'<br/>';
    //var_dump($this->map);
    echo $this->mapRenderer($this->map, array('height' => '500px',
                                              'width'  => '500px'));
}?>
