<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src= <?= $this->baseUrl('js/validation.js') ?>></script>


<?php /*$this->headScript()
    ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
    ->appendFile($this->baseUrl('js/editprofilevalidation.js'))*/
?>

<br/> 
  <h3><?php echo $this->msg; ?></h3>
  <?php
  for($a=0; $a<6; $a++){
      echo "<br/>";
  }
      echo $this->profileForm;
  ?>