<script type="text/javascript" src="<?php $this->baseUrl('js/jquery-1.12.4.min.js') ?>"></script>
<script type="text/javascript" src="<?php $this->baseUrl('js/validation.js') ?>"></script>

<?php /*$this->headScript()
    ->appendFile($this->baseUrl('js/ediprofilevalidation.js'))
    ->appendScript($this->baseUrl('js/jquery-1.12.4.min.js'))*/?>

<br/> 
  <h3><?php echo $this->msg; ?></h3>
  <?php
  for($a=0; $a<6; $a++){
      echo "<br/>";
  }
      echo $this->profileForm;
  ?>