<?php $this->headScript()
    ->appendFile($this->baseUrl('js/editprofilevalidation.js'))
    ->appendFile($this->baseUrl('js/jquery-1.12.4.min.js'))?>



<?php /*$this->headScript()
    ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
    ->appendFile($this->baseUrl('js/editprofilevalidation.js'))*/
?>

<br/> 
  <h3><?php echo $this->msg; ?></h3>
  <?php
  for($a=0; $a<6; $a++){
      echo "<br/>";
  }
      echo $this->profileForm;
  ?>