<?php $this->headScript()
    ->appendFile($this->baseUrl('js/jquery-1.12.4.min.js'),$type = 'text/javascript')
    ->appendFile($this->baseUrl('js/regex.js'),$type = 'text/javascript')?>


<div id="staff" class="container">
    
    <?php
    if($this->z)
        echo '<b>Modifica della zona '. $this->z .' del piano '. $this->fl .' dell immobile '. $this->i. '</b>';
    else {
        echo '<b>Inserimento di una nuova zona del piano '. $this->fl .' nell immobile '. $this->i .'</b>';
    }
    echo '<br>';
    echo $this->f;
    ?>


</div>