<div id="staff" class="container">

    <?php
    if($this->fl)
        echo '<b>Modifica del piano '. $this->fl .' dell immobile '. $this->imm. '</b>';
    else {
        echo '<b>Inserimento di un nuovo piano nell immobile '. $this->imm .'</b>';
    }
    echo '<br>';
    echo $this->ff;
    ?>


    <?php
    if($this->fl){
        echo '<hr>';
        echo '<b>Modifica delle zone del piano '. $this->fl .' dell immobile '. $this->imm. '</b>';
        echo $this->eff;
    }
    ?>

</div>