<div id="staff" class="container">
    
    <?php
    if($this->imm)
        echo '<h1><b>Modifica dell immobile '. $this->imm. '</b></h1>';
    else {
        echo '<h1><b>Inserisci un nuovo immobile</b></h1>';
    }
    echo '<br>';
    echo $this->pbuild;
    ?>
    
    
    <?php
    if($this->imm){
        echo '<hr>';
        echo '<b>Modifica dei piani dell immobile '. $this->imm. '</b>';
        echo $this->ebuild;
    }
    ?>
    
</div>