<br/> 
  <h3><?php echo $this->msg; ?></h3>
  <ul><li class="faqmenu"><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insertfaq'
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="0" title="">Inserisci Faq</a></li>
    <li class="faqmenu"><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'showfaq',
                        'edit'       => true
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="1" title="">Modifica Faq</a></li>  
    <li class="faqmenu"><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'showfaq',
                        'edit'       => false
                        ), 
                        'default',true
                    ); 
                 ?>" accesskey="2" title="">Cancella Faq</a></li> </ul>