<div id="staff" class="container">
    <br/>
    <div class="tablefaq">
        <?php 
        if ($this->_edituser == true)
            echo "<div ><h1> MODIFICA UTENTI.</h1></div>" ;
        else
            echo "<div ><h1> ELIMINA UTENTI.</h1></div>" ;
        ?>
        <br />
        <div>
            <table>
            	<?php  foreach (((object)$this->users) as $user) :?>
            	<tr>
            	<td><?php echo $user ?></td> 
            	</tr>   
        
        		<?php endforeach ?>
        	</table>
      </div>
    </div>
</div>