<div id="staff" class="container">

    <div class="tablefaq">
        <div ><h1 id="faq"> F.A.Q.</h1></div> <br />
        <div>
            <table>
            	<?php  foreach (((object)$this->faqs) as $faq) :?>
            	<tr>
            		<td><?php echo $faq ?></td>
            	</tr>   
        
        		<?php endforeach ?>
        	</table>
        	      
	  <?php if($this->products instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->products,'Sliding','public/_paginator.phtml');
	  } 
	  ?>

      </div>
    </div>
</div>